# -*- coding: utf-8 -*-
#
# Copyright (C) 2019, 2024-2025 Bob Swift (rdswift)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.


from picard.plugin3.api import PluginApi


class LanguageList():
    """Provides the language names for ISO 639-3 codes."""

    api: PluginApi = None
    language_map = {}

    def __init__(self):
        pass

    @classmethod
    def initialize(cls, api: PluginApi):
        cls.api = api
        cls.language_map = {
            'aar': api.tr('language.aar', "Afar"),
            'abk': api.tr('language.abk', "Abkhazian"),
            'ace': api.tr('language.ace', "Achinese"),
            'ach': api.tr('language.ach', "Acoli"),
            'ada': api.tr('language.ada', "Adangme"),
            'ady': api.tr('language.ady', "Adyghe / Adygei"),
            'afh': api.tr('language.afh', "Afrihili"),
            'afr': api.tr('language.afr', "Afrikaans"),
            'ain': api.tr('language.ain', "Ainu (Japan)"),
            'aka': api.tr('language.aka', "Akan"),
            'akk': api.tr('language.akk', "Akkadian"),
            'ale': api.tr('language.ale', "Aleut"),
            'alt': api.tr('language.alt', "Altai (Southern)"),
            'amh': api.tr('language.amh', "Amharic"),
            'ang': api.tr('language.ang', "Old English"),
            'anp': api.tr('language.anp', "Angika"),
            'ara': api.tr('language.ara', "Arabic"),
            'arc': api.tr('language.arc', "Aramaic"),
            'arg': api.tr('language.arg', "Aragonese"),
            'arn': api.tr('language.arn', "Araucanian"),
            'arp': api.tr('language.arp', "Arapaho"),
            'arw': api.tr('language.arw', "Arawak"),
            'asm': api.tr('language.asm', "Assamese"),
            'ast': api.tr('language.ast', "Asturian"),
            'ava': api.tr('language.ava', "Avaric"),
            'ave': api.tr('language.ave', "Avestan"),
            'awa': api.tr('language.awa', "Awadhi"),
            'aym': api.tr('language.aym', "Aymara"),
            'aze': api.tr('language.aze', "Azerbaijani"),
            'bak': api.tr('language.bak', "Bashkir"),
            'bal': api.tr('language.bal', "Baluchi"),
            'bam': api.tr('language.bam', "Bambara"),
            'ban': api.tr('language.ban', "Balinese"),
            'bas': api.tr('language.bas', "Basa (Cameroon)"),
            'bej': api.tr('language.bej', "Beja"),
            'bel': api.tr('language.bel', "Belarusian"),
            'bem': api.tr('language.bem', "Bemba (Zambia)"),
            'ben': api.tr('language.ben', "Bengali"),
            'bho': api.tr('language.bho', "Bhojpuri"),
            'bik': api.tr('language.bik', "Bikol"),
            'bin': api.tr('language.bin', "Bini"),
            'bis': api.tr('language.bis', "Bislama"),
            'bla': api.tr('language.bla', "Blackfoot"),
            'bod': api.tr('language.bod', "Tibetan"),
            'bos': api.tr('language.bos', "Bosnian"),
            'bra': api.tr('language.bra', "Braj"),
            'bre': api.tr('language.bre', "Breton"),
            'bua': api.tr('language.bua', "Buriat"),
            'bug': api.tr('language.bug', "Buginese"),
            'bul': api.tr('language.bul', "Bulgarian"),
            'byn': api.tr('language.byn', "Bilin"),
            'cad': api.tr('language.cad', "Caddo"),
            'car': api.tr('language.car', "Carib"),
            'cat': api.tr('language.cat', "Catalan"),
            'ceb': api.tr('language.ceb', "Cebuano"),
            'ces': api.tr('language.ces', "Czech"),
            'cha': api.tr('language.cha', "Chamorro"),
            'chb': api.tr('language.chb', "Chibcha"),
            'che': api.tr('language.che', "Chechen"),
            'chg': api.tr('language.chg', "Chagatai"),
            'chk': api.tr('language.chk', "Chuukese"),
            'chm': api.tr('language.chm', "Mari (Russia)"),
            'chn': api.tr('language.chn', "Chinook jargon"),
            'cho': api.tr('language.cho', "Choctaw"),
            'chp': api.tr('language.chp', "Chipewyan"),
            'chr': api.tr('language.chr', "Cherokee"),
            'chu': api.tr('language.chu', "Old Church Slavonic"),
            'chv': api.tr('language.chv', "Chuvash"),
            'chy': api.tr('language.chy', "Cheyenne"),
            'cnr': api.tr('language.cnr', "Montenegrin"),
            'cop': api.tr('language.cop', "Coptic"),
            'cor': api.tr('language.cor', "Cornish"),
            'cos': api.tr('language.cos', "Corsican"),
            'cre': api.tr('language.cre', "Cree"),
            'crh': api.tr('language.crh', "Crimean Tatar"),
            'csb': api.tr('language.csb', "Kashubian"),
            'cym': api.tr('language.cym', "Welsh"),
            'dak': api.tr('language.dak', "Dakota"),
            'dan': api.tr('language.dan', "Danish"),
            'dar': api.tr('language.dar', "Dargwa"),
            'del': api.tr('language.del', "Delaware"),
            'den': api.tr('language.den', "Slave (Athapascan)"),
            'deu': api.tr('language.deu', "German"),
            'dgr': api.tr('language.dgr', "Dogrib"),
            'din': api.tr('language.din', "Dinka"),
            'div': api.tr('language.div', "Divehi"),
            'doi': api.tr('language.doi', "Dogri (generic)"),
            'dsb': api.tr('language.dsb', "Sorbian, Lower"),
            'dua': api.tr('language.dua', "Duala"),
            'dum': api.tr('language.dum', "Dutch, Middle (ca.1050-1350)"),
            'dyu': api.tr('language.dyu', "Dyula"),
            'dzo': api.tr('language.dzo', "Dzongkha"),
            'efi': api.tr('language.efi', "Efik"),
            'egy': api.tr('language.egy', "Egyptian"),
            'eka': api.tr('language.eka', "Ekajuk"),
            'ell': api.tr('language.ell', "Greek"),
            'elx': api.tr('language.elx', "Elamite"),
            'eng': api.tr('language.eng', "English"),
            'enm': api.tr('language.enm', "English, Middle (1100-1500)"),
            'epo': api.tr('language.epo', "Esperanto"),
            'est': api.tr('language.est', "Estonian"),
            'eus': api.tr('language.eus', "Basque"),
            'ewe': api.tr('language.ewe', "Ewe"),
            'ewo': api.tr('language.ewo', "Ewondo"),
            'fan': api.tr('language.fan', "Fang (Equatorial Guinea)"),
            'fao': api.tr('language.fao', "Faroese"),
            'fas': api.tr('language.fas', "Persian"),
            'fat': api.tr('language.fat', "Fanti"),
            'fij': api.tr('language.fij', "Fijian"),
            'fil': api.tr('language.fil', "Filipino"),
            'fin': api.tr('language.fin', "Finnish"),
            'fon': api.tr('language.fon', "Fon"),
            'fra': api.tr('language.fra', "French"),
            'frm': api.tr('language.frm', "French, Middle (ca.1400-1600)"),
            'fro': api.tr('language.fro', "French, Old (842-Ca.1400)"),
            'frr': api.tr('language.frr', "Frisian, Northern"),
            'frs': api.tr('language.frs', "Frisian, Eastern"),
            'fry': api.tr('language.fry', "Frisian, Western"),
            'ful': api.tr('language.ful', "Fulah"),
            'fur': api.tr('language.fur', "Friulian"),
            'gaa': api.tr('language.gaa', "Ga"),
            'gay': api.tr('language.gay', "Gayo"),
            'gba': api.tr('language.gba', "Gbaya (Central African Republic)"),
            'gez': api.tr('language.gez', "Geez"),
            'gil': api.tr('language.gil', "Gilbertese"),
            'gla': api.tr('language.gla', "Gaelic (Scots)"),
            'gle': api.tr('language.gle', "Irish"),
            'glg': api.tr('language.glg', "Galician"),
            'glv': api.tr('language.glv', "Manx"),
            'gmh': api.tr('language.gmh', "German, Middle High (ca.1050-1500)"),
            'goh': api.tr('language.goh', "German, Old High (ca.750-1050)"),
            'gon': api.tr('language.gon', "Gondi"),
            'gor': api.tr('language.gor', "Gorontalo"),
            'got': api.tr('language.got', "Gothic"),
            'grb': api.tr('language.grb', "Grebo"),
            'grc': api.tr('language.grc', "Greek, Ancient (to 1453)"),
            'grn': api.tr('language.grn', "Guarani"),
            'gsw': api.tr('language.gsw', "Swiss German, Alemannic, Alsatian"),
            'guj': api.tr('language.guj', "Gujarati"),
            'gwi': api.tr('language.gwi', "Gwich'in"),
            'hai': api.tr('language.hai', "Haida"),
            'hat': api.tr('language.hat', "Haitian / Haitian Creole"),
            'hau': api.tr('language.hau', "Hausa"),
            'haw': api.tr('language.haw', "Hawaiian"),
            'heb': api.tr('language.heb', "Hebrew"),
            'her': api.tr('language.her', "Herero"),
            'hil': api.tr('language.hil', "Hiligaynon"),
            'hin': api.tr('language.hin', "Hindi"),
            'hit': api.tr('language.hit', "Hittite"),
            'hmn': api.tr('language.hmn', "Hmong"),
            'hmo': api.tr('language.hmo', "Hiri Motu"),
            'hrv': api.tr('language.hrv', "Croatian"),
            'hsb': api.tr('language.hsb', "Sorbian, Upper"),
            'hun': api.tr('language.hun', "Hungarian"),
            'hup': api.tr('language.hup', "Hupa"),
            'hye': api.tr('language.hye', "Armenian"),
            'iba': api.tr('language.iba', "Iban"),
            'ibo': api.tr('language.ibo', "Igbo"),
            'ido': api.tr('language.ido', "Ido"),
            'iii': api.tr('language.iii', "Yi, Sichuan"),
            'iku': api.tr('language.iku', "Inuktitut"),
            'ile': api.tr('language.ile', "Interlingue"),
            'ilo': api.tr('language.ilo', "Iloko"),
            'ina': api.tr('language.ina', "Interlingua"),
            'ind': api.tr('language.ind', "Indonesian"),
            'inh': api.tr('language.inh', "Ingush"),
            'ipk': api.tr('language.ipk', "Inupiaq"),
            'isl': api.tr('language.isl', "Icelandic"),
            'ita': api.tr('language.ita', "Italian"),
            'jav': api.tr('language.jav', "Javanese"),
            'jbo': api.tr('language.jbo', "Lojban"),
            'jpn': api.tr('language.jpn', "Japanese"),
            'jpr': api.tr('language.jpr', "Judeo-Persian"),
            'jrb': api.tr('language.jrb', "Judeo-Arabic"),
            'kaa': api.tr('language.kaa', "Karakalpak"),
            'kab': api.tr('language.kab', "Kabyle"),
            'kac': api.tr('language.kac', "Jingpho"),
            'kal': api.tr('language.kal', "Kalaallisut"),
            'kam': api.tr('language.kam', "Kamba (Kenya)"),
            'kan': api.tr('language.kan', "Kannada"),
            'kas': api.tr('language.kas', "Kashmiri"),
            'kat': api.tr('language.kat', "Georgian"),
            'kau': api.tr('language.kau', "Kanuri"),
            'kaw': api.tr('language.kaw', "Kawi"),
            'kaz': api.tr('language.kaz', "Kazakh"),
            'kbd': api.tr('language.kbd', "Kabardian"),
            'kha': api.tr('language.kha', "Khasi"),
            'khm': api.tr('language.khm', "Khmer"),
            'kho': api.tr('language.kho', "Khotanese"),
            'kik': api.tr('language.kik', "Kikuyu"),
            'kin': api.tr('language.kin', "Kinyarwanda"),
            'kir': api.tr('language.kir', "Kyrgyz"),
            'kmb': api.tr('language.kmb', "Kimbundu"),
            'kok': api.tr('language.kok', "Konkani (generic)"),
            'kom': api.tr('language.kom', "Komi"),
            'kon': api.tr('language.kon', "Kongo"),
            'kor': api.tr('language.kor', "Korean"),
            'kos': api.tr('language.kos', "Kosraean"),
            'kpe': api.tr('language.kpe', "Kpelle"),
            'krc': api.tr('language.krc', "Karachay-Balkar"),
            'krl': api.tr('language.krl', "Karelian"),
            'kru': api.tr('language.kru', "Kurukh"),
            'kua': api.tr('language.kua', "Kuanyama"),
            'kum': api.tr('language.kum', "Kumyk"),
            'kur': api.tr('language.kur', "Kurdish"),
            'kut': api.tr('language.kut', "Kutenai"),
            'lad': api.tr('language.lad', "Ladino"),
            'lah': api.tr('language.lah', "Lahnda"),
            'lam': api.tr('language.lam', "Lamba"),
            'lao': api.tr('language.lao', "Lao"),
            'lat': api.tr('language.lat', "Latin"),
            'lav': api.tr('language.lav', "Latvian"),
            'lez': api.tr('language.lez', "Lezghian"),
            'lim': api.tr('language.lim', "Limburgish, Limburgan"),
            'lin': api.tr('language.lin', "Lingala"),
            'lit': api.tr('language.lit', "Lithuanian"),
            'lol': api.tr('language.lol', "Mongo"),
            'loz': api.tr('language.loz', "Lozi"),
            'ltz': api.tr('language.ltz', "Luxembourgish / Letzeburgesch"),
            'lua': api.tr('language.lua', "Luba-Lulua"),
            'lub': api.tr('language.lub', "Luba-Katanga"),
            'lug': api.tr('language.lug', "Luganda"),
            'lui': api.tr('language.lui', "Luiseno"),
            'lun': api.tr('language.lun', "Lunda"),
            'luo': api.tr('language.luo', "Luo (Kenya and Tanzania)"),
            'lus': api.tr('language.lus', "Lushai"),
            'mad': api.tr('language.mad', "Madurese"),
            'mag': api.tr('language.mag', "Magahi"),
            'mah': api.tr('language.mah', "Marshall"),
            'mai': api.tr('language.mai', "Maithili"),
            'mak': api.tr('language.mak', "Makasar"),
            'mal': api.tr('language.mal', "Malayalam"),
            'man': api.tr('language.man', "Mandingo"),
            'mar': api.tr('language.mar', "Marathi"),
            'mas': api.tr('language.mas', "Masai"),
            'mdf': api.tr('language.mdf', "Moksha"),
            'mdr': api.tr('language.mdr', "Mandar"),
            'men': api.tr('language.men', "Mende (Sierra Leone)"),
            'mga': api.tr('language.mga', "Irish, Middle (900-1200)"),
            'mic': api.tr('language.mic', "Micmac"),
            'min': api.tr('language.min', "Minangkabau"),
            'mis': api.tr('language.mis', "Uncoded languages"),
            'mkd': api.tr('language.mkd', "Macedonian"),
            'mlg': api.tr('language.mlg', "Malagasy"),
            'mlt': api.tr('language.mlt', "Maltese"),
            'mnc': api.tr('language.mnc', "Manchu"),
            'mni': api.tr('language.mni', "Meitei"),
            'moh': api.tr('language.moh', "Mohawk"),
            'mon': api.tr('language.mon', "Mongolian"),
            'mos': api.tr('language.mos', "Mossi"),
            'mri': api.tr('language.mri', "Maori"),
            'msa': api.tr('language.msa', "Malay (generic)"),
            'mul': api.tr('language.mul', "Multiple languages"),
            'mus': api.tr('language.mus', "Creek"),
            'mwl': api.tr('language.mwl', "Mirandese"),
            'mwr': api.tr('language.mwr', "Marwari"),
            'mya': api.tr('language.mya', "Burmese"),
            'myv': api.tr('language.myv', "Erzya"),
            'nap': api.tr('language.nap', "Neapolitan"),
            'nau': api.tr('language.nau', "Nauru"),
            'nav': api.tr('language.nav', "Navajo"),
            'nbl': api.tr('language.nbl', "Ndebele, South"),
            'nde': api.tr('language.nde', "Ndebele, North"),
            'ndo': api.tr('language.ndo', "Ndonga"),
            'nds': api.tr('language.nds', "Low German / Low Saxon"),
            'nep': api.tr('language.nep', "Nepali"),
            'new': api.tr('language.new', "Newari / Nepal Bhasa"),
            'nia': api.tr('language.nia', "Nias"),
            'niu': api.tr('language.niu', "Niuean"),
            'nld': api.tr('language.nld', "Dutch"),
            'nno': api.tr('language.nno', "Norwegian Nynorsk"),
            'nob': api.tr('language.nob', "Norwegian Bokmål"),
            'nog': api.tr('language.nog', "Nogai"),
            'non': api.tr('language.non', "Norse, Old"),
            'nor': api.tr('language.nor', "Norwegian"),
            'nqo': api.tr('language.nqo', "N'Ko"),
            'nso': api.tr('language.nso', "Northern Sotho, Pedi / Sepedi"),
            'nwc': api.tr('language.nwc', "Classical Newari / Old Newari"),
            'nya': api.tr('language.nya', "Chichewa / Nyanja"),
            'nym': api.tr('language.nym', "Nyamwezi"),
            'nyn': api.tr('language.nyn', "Nyankole"),
            'nyo': api.tr('language.nyo', "Nyoro"),
            'nzi': api.tr('language.nzi', "Nzima"),
            'oci': api.tr('language.oci', "Occitan (post 1500)"),
            'oji': api.tr('language.oji', "Ojibwa"),
            'ori': api.tr('language.ori', "Oriya"),
            'orm': api.tr('language.orm', "Oromo"),
            'osa': api.tr('language.osa', "Osage"),
            'oss': api.tr('language.oss', "Ossetian"),
            'ota': api.tr('language.ota', "Turkish, Ottoman (1500-1928)"),
            'pag': api.tr('language.pag', "Pangasinan"),
            'pal': api.tr('language.pal', "Pahlavi"),
            'pam': api.tr('language.pam', "Pampanga"),
            'pan': api.tr('language.pan', "Panjabi / Punjabi"),
            'pap': api.tr('language.pap', "Papiamento"),
            'pau': api.tr('language.pau', "Palauan"),
            'peo': api.tr('language.peo', "Persian, Old (ca.600-400 B.C.)"),
            'phn': api.tr('language.phn', "Phoenician"),
            'pli': api.tr('language.pli', "Pali"),
            'pol': api.tr('language.pol', "Polish"),
            'pon': api.tr('language.pon', "Pohnpeian"),
            'por': api.tr('language.por', "Portuguese"),
            'pro': api.tr('language.pro', "Provençal, Old (to 1500)"),
            'pus': api.tr('language.pus', "Pushto"),
            'qaa': api.tr('language.qaa', "Artificial"),
            'que': api.tr('language.que', "Quechua"),
            'raj': api.tr('language.raj', "Rajasthani"),
            'rap': api.tr('language.rap', "Rapanui"),
            'rar': api.tr('language.rar', "Rarotongan"),
            'roh': api.tr('language.roh', "Raeto-Romance"),
            'rom': api.tr('language.rom', "Romany"),
            'ron': api.tr('language.ron', "Romanian"),
            'run': api.tr('language.run', "Rundi"),
            'rup': api.tr('language.rup', "Aromanian"),
            'rus': api.tr('language.rus', "Russian"),
            'sad': api.tr('language.sad', "Sandawe"),
            'sag': api.tr('language.sag', "Sango"),
            'sah': api.tr('language.sah', "Sakha"),
            'sam': api.tr('language.sam', "Aramaic, Samaritan"),
            'san': api.tr('language.san', "Sanskrit"),
            'sas': api.tr('language.sas', "Sasak"),
            'sat': api.tr('language.sat', "Santali"),
            'scn': api.tr('language.scn', "Sicilian"),
            'sco': api.tr('language.sco', "Scots"),
            'sel': api.tr('language.sel', "Selkup"),
            'sga': api.tr('language.sga', "Old Irish"),
            'shn': api.tr('language.shn', "Shan"),
            'sid': api.tr('language.sid', "Sidamo"),
            'sin': api.tr('language.sin', "Sinhala / Sinhalese"),
            'slk': api.tr('language.slk', "Slovak"),
            'slv': api.tr('language.slv', "Slovenian"),
            'sma': api.tr('language.sma', "Southern Sami"),
            'sme': api.tr('language.sme', "Northern Sami"),
            'smj': api.tr('language.smj', "Lule Sami"),
            'smn': api.tr('language.smn', "Inari Sami"),
            'smo': api.tr('language.smo', "Samoan"),
            'sms': api.tr('language.sms', "Skolt Sami"),
            'sna': api.tr('language.sna', "Shona"),
            'snd': api.tr('language.snd', "Sindhi"),
            'snk': api.tr('language.snk', "Soninke"),
            'sog': api.tr('language.sog', "Sogdian"),
            'som': api.tr('language.som', "Somali"),
            'sot': api.tr('language.sot', "Sotho, Southern"),
            'spa': api.tr('language.spa', "Spanish (Castilian)"),
            'sqi': api.tr('language.sqi', "Albanian"),
            'srd': api.tr('language.srd', "Sardinian"),
            'srn': api.tr('language.srn', "Sranan"),
            'srp': api.tr('language.srp', "Serbian"),
            'srr': api.tr('language.srr', "Serer"),
            'ssw': api.tr('language.ssw', "Swati"),
            'suk': api.tr('language.suk', "Sukuma"),
            'sun': api.tr('language.sun', "Sundanese"),
            'sus': api.tr('language.sus', "Susu"),
            'sux': api.tr('language.sux', "Sumerian"),
            'swa': api.tr('language.swa', "Swahili (generic)"),
            'swe': api.tr('language.swe', "Swedish"),
            'syc': api.tr('language.syc', "Syriac, Classical"),
            'syr': api.tr('language.syr', "Syriac"),
            'tah': api.tr('language.tah', "Tahitian"),
            'tam': api.tr('language.tam', "Tamil"),
            'tat': api.tr('language.tat', "Tatar"),
            'tel': api.tr('language.tel', "Telugu"),
            'tem': api.tr('language.tem', "Time"),
            'ter': api.tr('language.ter', "Tereno"),
            'tet': api.tr('language.tet', "Tetum"),
            'tgk': api.tr('language.tgk', "Tajik"),
            'tgl': api.tr('language.tgl', "Tagalog"),
            'tha': api.tr('language.tha', "Thai"),
            'tig': api.tr('language.tig', "Tigre"),
            'tir': api.tr('language.tir', "Tigrinya"),
            'tiv': api.tr('language.tiv', "Tiv"),
            'tkl': api.tr('language.tkl', "Tokelau"),
            'tlh': api.tr('language.tlh', "Klingon / tlhIngan-Hol"),
            'tli': api.tr('language.tli', "Tlingit"),
            'tmh': api.tr('language.tmh', "Tamashek"),
            'tog': api.tr('language.tog', "Tonga (Nyasa)"),
            'ton': api.tr('language.ton', "Tonga (Tonga Islands)"),
            'tpi': api.tr('language.tpi', "Tok Pisin"),
            'tsi': api.tr('language.tsi', "Tsimshian"),
            'tsn': api.tr('language.tsn', "Tswana"),
            'tso': api.tr('language.tso', "Tsonga"),
            'tuk': api.tr('language.tuk', "Turkmen"),
            'tum': api.tr('language.tum', "Tumbuka"),
            'tur': api.tr('language.tur', "Turkish"),
            'tvl': api.tr('language.tvl', "Tuvalu"),
            'twi': api.tr('language.twi', "Twi"),
            'tyv': api.tr('language.tyv', "Tuvinian"),
            'udm': api.tr('language.udm', "Udmurt"),
            'uga': api.tr('language.uga', "Ugaritic"),
            'uig': api.tr('language.uig', "Uighur"),
            'ukr': api.tr('language.ukr', "Ukrainian"),
            'umb': api.tr('language.umb', "Umbundu"),
            'und': api.tr('language.und', "Undetermined"),
            'urd': api.tr('language.urd', "Urdu"),
            'uzb': api.tr('language.uzb', "Uzbek"),
            'vai': api.tr('language.vai', "Vai"),
            'ven': api.tr('language.ven', "Venda"),
            'vie': api.tr('language.vie', "Vietnamese"),
            'vol': api.tr('language.vol', "Volapük"),
            'vot': api.tr('language.vot', "Votic"),
            'wal': api.tr('language.wal', "Wolaitta"),
            'war': api.tr('language.war', "Waray (Philippines)"),
            'was': api.tr('language.was', "Washo"),
            'wln': api.tr('language.wln', "Walloon"),
            'wol': api.tr('language.wol', "Wolof"),
            'xal': api.tr('language.xal', "Kalmyk / Oirat"),
            'xho': api.tr('language.xho', "Xhosa"),
            'yao': api.tr('language.yao', "Yao"),
            'yap': api.tr('language.yap', "Yapese"),
            'yid': api.tr('language.yid', "Yiddish"),
            'yor': api.tr('language.yor', "Yoruba"),
            'zap': api.tr('language.zap', "Zapotec"),
            'zbl': api.tr('language.zbl', "Blissymbols"),
            'zen': api.tr('language.zen', "Zenaga"),
            'zgh': api.tr('language.zgh', "Standard Moroccan Tamazight"),
            'zha': api.tr('language.zha', "Zhuang"),
            'zho': api.tr('language.zho', "Chinese"),
            'zul': api.tr('language.zul', "Zulu"),
            'zun': api.tr('language.zun', "Zuni"),
            'zxx': api.tr('language.zxx', "No linguistic content"),
            'zza': api.tr('language.zza', "Zaza / Dimili"),
        }

    @classmethod
    def get_language(cls, language_code: str) -> str:
        """Return the full language name from the configured language list for
        the supplied three-character language code.

        Args:
            text (str): Language code

        Returns:
            str: Full name of the language
        """
        return cls.language_map[language_code] if language_code in cls.language_map else 'unknown'


def func_language_name(parser, text: str) -> str:
    """Return the full language name for the supplied language code.

    Args:
        _parser (ScriptParser): Script parser used by the tagger
        text (str): Language code

    Returns:
        str: Full name of the language
    """
    text = text.strip().lower()
    if text:
        return LanguageList.get_language(text)
    return 'missing'


def enable(api: PluginApi):
    """Called when plugin is enabled."""
    LanguageList.initialize(api)

    api.register_script_function(
        func_language_name,
        name='language_name',
        signature=api.tr("help.language_name.signature", "$language_name(code)"),
        documentation=api.tr(
            "help.language_name.documentation",
            (
                "Returns the full name of a language for the ISO 639-3 three-character language "
                "code provided. If an unknown code is entered, the function will return '**unknown**'. "
                "If there is no code entered, '**missing**' will be returned."
            )
        )
    )
